// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: internal/infra/grpc/proto/meter.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Meter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Brand  string `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Serial string `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	Lines  int32  `protobuf:"varint,3,opt,name=lines,proto3" json:"lines,omitempty"`
}

func (x *Meter) Reset() {
	*x = Meter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_infra_grpc_proto_meter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Meter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meter) ProtoMessage() {}

func (x *Meter) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_grpc_proto_meter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meter.ProtoReflect.Descriptor instead.
func (*Meter) Descriptor() ([]byte, []int) {
	return file_internal_infra_grpc_proto_meter_proto_rawDescGZIP(), []int{0}
}

func (x *Meter) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Meter) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *Meter) GetLines() int32 {
	if x != nil {
		return x.Lines
	}
	return 0
}

type CreateMeterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meter *Meter `protobuf:"bytes,1,opt,name=meter,proto3" json:"meter,omitempty"`
}

func (x *CreateMeterReq) Reset() {
	*x = CreateMeterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_infra_grpc_proto_meter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMeterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeterReq) ProtoMessage() {}

func (x *CreateMeterReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_grpc_proto_meter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeterReq.ProtoReflect.Descriptor instead.
func (*CreateMeterReq) Descriptor() ([]byte, []int) {
	return file_internal_infra_grpc_proto_meter_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMeterReq) GetMeter() *Meter {
	if x != nil {
		return x.Meter
	}
	return nil
}

type CreateMeterResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MeterId string `protobuf:"bytes,1,opt,name=meterId,proto3" json:"meterId,omitempty"`
}

func (x *CreateMeterResp) Reset() {
	*x = CreateMeterResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_infra_grpc_proto_meter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMeterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeterResp) ProtoMessage() {}

func (x *CreateMeterResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_grpc_proto_meter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeterResp.ProtoReflect.Descriptor instead.
func (*CreateMeterResp) Descriptor() ([]byte, []int) {
	return file_internal_infra_grpc_proto_meter_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMeterResp) GetMeterId() string {
	if x != nil {
		return x.MeterId
	}
	return ""
}

type ListMeterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MeterId string `protobuf:"bytes,1,opt,name=meterId,proto3" json:"meterId,omitempty"`
}

func (x *ListMeterReq) Reset() {
	*x = ListMeterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_infra_grpc_proto_meter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMeterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMeterReq) ProtoMessage() {}

func (x *ListMeterReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infra_grpc_proto_meter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMeterReq.ProtoReflect.Descriptor instead.
func (*ListMeterReq) Descriptor() ([]byte, []int) {
	return file_internal_infra_grpc_proto_meter_proto_rawDescGZIP(), []int{3}
}

func (x *ListMeterReq) GetMeterId() string {
	if x != nil {
		return x.MeterId
	}
	return ""
}

var File_internal_infra_grpc_proto_meter_proto protoreflect.FileDescriptor

var file_internal_infra_grpc_proto_meter_proto_rawDesc = []byte{
	0x0a, 0x25, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b,
	0x0a, 0x05, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x22, 0x34, 0x0a, 0x0e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a,
	0x05, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x05, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x22, 0x2b, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x28,
	0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x49, 0x64, 0x32, 0x47, 0x0a, 0x0c, 0x4d, 0x65, 0x74, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x42, 0x1d, 0x5a, 0x1b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x6e,
	0x66, 0x72, 0x61, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_infra_grpc_proto_meter_proto_rawDescOnce sync.Once
	file_internal_infra_grpc_proto_meter_proto_rawDescData = file_internal_infra_grpc_proto_meter_proto_rawDesc
)

func file_internal_infra_grpc_proto_meter_proto_rawDescGZIP() []byte {
	file_internal_infra_grpc_proto_meter_proto_rawDescOnce.Do(func() {
		file_internal_infra_grpc_proto_meter_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_infra_grpc_proto_meter_proto_rawDescData)
	})
	return file_internal_infra_grpc_proto_meter_proto_rawDescData
}

var file_internal_infra_grpc_proto_meter_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_infra_grpc_proto_meter_proto_goTypes = []interface{}{
	(*Meter)(nil),           // 0: proto.Meter
	(*CreateMeterReq)(nil),  // 1: proto.CreateMeterReq
	(*CreateMeterResp)(nil), // 2: proto.CreateMeterResp
	(*ListMeterReq)(nil),    // 3: proto.ListMeterReq
}
var file_internal_infra_grpc_proto_meter_proto_depIdxs = []int32{
	0, // 0: proto.CreateMeterReq.meter:type_name -> proto.Meter
	1, // 1: proto.MeterService.Create:input_type -> proto.CreateMeterReq
	2, // 2: proto.MeterService.Create:output_type -> proto.CreateMeterResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_infra_grpc_proto_meter_proto_init() }
func file_internal_infra_grpc_proto_meter_proto_init() {
	if File_internal_infra_grpc_proto_meter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_infra_grpc_proto_meter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Meter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_infra_grpc_proto_meter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMeterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_infra_grpc_proto_meter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMeterResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_infra_grpc_proto_meter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMeterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_infra_grpc_proto_meter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_infra_grpc_proto_meter_proto_goTypes,
		DependencyIndexes: file_internal_infra_grpc_proto_meter_proto_depIdxs,
		MessageInfos:      file_internal_infra_grpc_proto_meter_proto_msgTypes,
	}.Build()
	File_internal_infra_grpc_proto_meter_proto = out.File
	file_internal_infra_grpc_proto_meter_proto_rawDesc = nil
	file_internal_infra_grpc_proto_meter_proto_goTypes = nil
	file_internal_infra_grpc_proto_meter_proto_depIdxs = nil
}
